
default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= Rails.application.credentials.DB_NAME.dev_db %>
  # username: <%= Rails.application.credentials.DB_USERNAME.dev_db %>
  # password: <%= Rails.application.credentials.DB_PASSWORD.dev_db %>

test:
  <<: *default
  database: <%= Rails.application.credentials.DB_NAME.test_db %>
  # username: <%= Rails.application.credentials.DB_USERNAME.test_db %>
  # password: <%= Rails.application.credentials.DB_PASSWORD.test_db %>

production:
  <<: *default
  database: <%= Rails.application.credentials.DB_NAME.prod_db %>
  username: <%= Rails.application.credentials.DB_USERNAME.prod_db %>
  password: <%= Rails.application.credentials.DB_PASSWORD.prod_db %>

